import os
import time
import sys

# Add project root to sys.path
current_dir = os.path.dirname(os.path.abspath(__file__))
if current_dir not in sys.path:
    sys.path.append(current_dir)

from log_cleaner import LogCleaner
from database_manager import DatabaseManager
from extract_crash import extract_crash



def main():
    # Target log file path
    
    log_file_path = "/home/amlogic/RAG/clean_log/store_log_data/IPTV-27435/failed/IPTV-27435_BJ-IPTV-26084-h264-花屏.log"
    if not os.path.exists(log_file_path):
        print(f"Error: Log file not found at {log_file_path}")
        return
    
    # 0. Extract crashes from log file
    extract_crash(log_file_path)
    start_time = time.time()

    # 1. Clean the log (Use existing logic to get cleaned content for comparison)
    cleaner = LogCleaner(log_file_path)
    clean_file_path, all_log_content = cleaner.clean_log()

    if not clean_file_path or not os.path.exists(clean_file_path):
        print("Log cleaning failed.")
        return

    # 2. Connect to Database to get existing cleaned logs
    db_path = os.path.join("/home/amlogic/RAG/clean_log/store_log_data", "log_data.db")
    db_manager = DatabaseManager(db_path)
    
    if not db_manager.connect():
        print("Failed to connect to database.")
        return
    
    # Ensure table exists (though we are only reading)
    db_manager.create_table()
    existing_cleaned_logs = db_manager.get_existing_cleaned_logs()
    db_manager.close()
    
    print(f"Loaded {len(existing_cleaned_logs)} existing cleaned logs from database.")

    # 3. Filter and write unique raw lines to a new file
    unique_lines = []
    
    # We need to map cleaned content back to raw lines or iterate carefully.
    # Since all_log_content keys are cleaned logs and values are line numbers (or sort keys),
    # and we have the clean_file_path which contains the intermediate result (usually raw lines with line numbers or processed lines).
    
    # Wait, the user requirement says:
    # "要求输出的内容不做 raw_log = line.split(':', 1)[1].strip() ... 这一层处理"
    # This implies we want the ORIGINAL line content corresponding to the unique cleaned log.
    
    # However, clean_log_stage_one_multi returns:
    # 1. clean_file_path: A file where lines might have been modified/filtered.
    # 2. all_log_content: A dict {cleaned_line: sort_index}
    
    # To get the "original" line without the specific split processing, we should look at 'clean_file_path' content again.
    # In 'run_clean_log.py' / 'log_cleaner.py', we saw that 'clean_file_path' contains lines that are read and then optionally split.
    # The user wants to SKIP the split.
    
    # Let's read the intermediate clean file.
    # Note: The intermediate file generated by clean_log_stage_one_multi contains lines that might already be partially processed 
    # (e.g., timestamps removed? No, stage one usually does some cleaning).
    # BUT, based on the user's reference to `raw_log = line.split...`, they are referring to the post-processing step in the main loop.
    # So we just need to read the lines from `clean_file_path` and NOT do the split.
    
    # But we need to filter them based on whether their *cleaned version* is in the DB.
    # We have `all_log_content` which maps {cleaned_line: index}.
    # We also have the file at `clean_file_path`.
    # We need to match them up.
    
    # The 'all_log_content' has keys which are the cleaned versions.
    # The 'clean_file_path' has the lines. 
    # The order in 'clean_file_path' corresponds to the sorted order of 'all_log_content' values? 
    # Let's verify: In `utils.py`, `clean_log_stage_one_multi` writes to `clean_file_path` based on sorted indices.
    # So the lines in `clean_file_path` correspond 1-to-1 with `sorted(all_log_content.items(), key=lambda item: item[1])`.
    
    unique_raw_lines = []
    
    with open(clean_file_path, 'r', encoding='utf-8', errors='ignore') as f:
        file_lines = f.readlines()
        
    # Validation
    if len(file_lines) != len(all_log_content):
        print(f"Warning: Line count mismatch. File: {len(file_lines)}, Dict: {len(all_log_content)}")
        # If mismatch, we might have issues matching. But usually they match if stage_one logic holds.
        min_len = min(len(file_lines), len(all_log_content))
    else:
        min_len = len(file_lines)
        
    skipped_count = 0
    
    for i in range(min_len):
        cleaned_log_key = all_log_content[i][0].strip()
        raw_line_from_file = file_lines[i].strip() # We strip whitespace but DO NOT split by ':'
        
        if cleaned_log_key not in existing_cleaned_logs:
            unique_raw_lines.append(raw_line_from_file)
            # Add to local set to handle duplicates within the current file itself
            existing_cleaned_logs.add(cleaned_log_key)
        else:
            skipped_count += 1
            
    # 4. Write to local file
    output_filename = f"filtered_unique_{os.path.basename(log_file_path)}"
    output_path = os.path.join(os.path.dirname(log_file_path), output_filename)
    
    with open(output_path, 'w', encoding='utf-8') as out_f:
        for line in unique_raw_lines:
            out_f.write(line + "\n")
            
    end_time = time.time()
    
    print(f"Filter completed in {end_time - start_time:.2f} seconds.")
    print(f"Total lines processed: {min_len}")
    print(f"Skipped (already in DB): {skipped_count}")
    print(f"New unique lines found: {len(unique_raw_lines)}")
    print(f"Unique lines written to: {output_path}")

if __name__ == "__main__":
    main()
